### ISSUE TITLE
Add E-Divisive means algorithm to the available change detection models

### ISSUE THREAD

**Issue by smalleni** [Hyperfoil/Horreum#1007]
**Feature idea.**

There is a lot of research and existing applications around using E-Divisive means for identifying change points in software performance data. See: https://arxiv.org/pdf/2003.00584.pdf Hence, it would be good to have that added to the current available changepoint detection models in Horreum.
**Describe the solution you'd like**

Add E-Divisive means based change point detection model here: https://github.com/Hyperfoil/Horreum/tree/master/horreum-backend/src/main/java/io/hyperfoil/tools/horreum/changedetection

**Comment by johnaohara** [comment]
Hi @smalleni thanks for the suggestion.

This is an algorithm that we have discussed implementing in the past. and have recoded some of the disucssion in various discussions/issues;

https://github.com/Hyperfoil/Horreum/discussions/913
https://github.com/Hyperfoil/Horreum/issues/38

The implementation (hunter: https://github.com/datastax-labs/hunter) that we were planning on using is detailed in this paper: https://arxiv.org/pdf/2301.03034.pdf  and has been used in production with mongoDB for a number of years.

There are a number of implementation details that we need to perform before we integrate Hunter;

- Polyglot language support: a lot of algorithms/libraries are created in python/R, we need to support multiple languages in order to not re-create each algorithm in Java
- Batch processing: currently, Horreum supports a continual monotonic time-series of data.  Algorithms like eDivisive Mean require batch processing of the entire dataset and we need to design into Horreum how to handle deltas in historic change point detection and the implications for notifications/change storage etc.  I.e. if we run eDivisive one week and get 4 changes detected, then re-run a week later and get 3, then how do we handle the differences in the UI/reporting etc.  The same applies to if the algorithm detects different changes between runs.
