### ISSUE TITLE
runs ordering by execution time does not work as expected

### ISSUE THREAD

**Issue by jhutar** [Hyperfoil/Horreum#1180]
**Describe the bug**
Runs ordering by execution time does not work as expected. I'm getting "8 days ago" above "4 hours ago" when ordered with a arrow pointing down.

**To Reproduce**
Go to https://horreum.corp.redhat.com/run/list/254 and click at "Executed" header to have a arrow pointing down

**Version**
Current version in Prod

**OS**
Fedora release 39 (Thirty Nine)

**Browser**
firefox-121.0.1-1.fc39.x86_64

![image](https://github.com/Hyperfoil/Horreum/assets/3397250/56a3ac3c-6a39-4a6b-a201-3e852f768ded)

**Comment by whitingjr** [comment]
@lampajr no PR was created to update master.

**Comment by lampajr** [comment]
After further analysis from `0.11.6` the `api/run/list/254?direction=Descending&limit=20&page=1&sort=start&trashed=false` call actually returns the data correctly ordered.

Furthermore when the `Executed` column is not ordered, the data is correctly ordered using the default ordering (`executed` and `Descending`):
![image](https://github.com/Hyperfoil/Horreum/assets/26715795/4fe9028c-b8c6-4ecf-9a54-b62687fe3588)

This means that most likely there was an issue on the Frontend (i.e., just client-side) that was ordering from bottom-to-top the results (already ordered by Backend), thus the issue.

I tried to reproduce the same in `master` branch without success, therefore I think this has been indirectly fixed in as part of other developments.

**Comment by whitingjr** [comment]
@lampajr we should revisit this after the 0.12 release is deployed.

**Comment by whitingjr** [comment]
Ordering is working as expected in the 0.12 release.
