### ISSUE TITLE
 Fix the OpenAPI spec to generate correct python client

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#1278]
**Describe the bug**

Fix the OpenAPI spec to generate correct python client: see https://github.com/Hyperfoil/horreum-client-python/issues/1#issuecomment-1928116857

**Comment by willr3** [comment]
Assuming we plan to use `openapi-python-client` to generate the client
```
openapi-python-client generate --path /tmp/openapi.yaml
```
Then our existing API is not compatible because it does not support content type `text/plain` 
```
Generating horreum-rest-api-client
Warning(s) encountered while generating. Client was generated, but some pieces may be missing

WARNING parsing POST /api/run/{id}/description within run. Endpoint will not be generated.

Unsupported content type text/plain


WARNING parsing POST /api/run/{id}/schema within run. Endpoint will not be generated.

Unsupported content type text/plain
```
We can either change our content type or help with 
https://github.com/openapi-generators/openapi-python-client/discussions/821

In the interim I have a PR for changes that resolve the rest of the API generation issues in the `openapi-python-client` output.
https://github.com/Hyperfoil/Horreum/pull/1335
