### ISSUE TITLE
Unable to retrieve action logs due to row level security

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#1353]
**Describe the bug**

calls to '/api/log/action/{testId}' always fail to retrieve the action logs because the logs are inserted as `horreum.system` and retrieved as user roles either `horreum.system` or an `admin` user: https://github.com/Hyperfoil/Horreum/blob/master/horreum-backend/src/main/resources/db/changeLog.xml#L3883

However, to role allowed on the REST endpoint is `tester`: https://github.com/Hyperfoil/Horreum/blob/master/horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/LogServiceImpl.java#L140

so, once the action logs have been created, only horreum system can retrieve them, and they are not accessible for users

**Comment by johnaohara** [comment]
Hmm, this is not strictly true, as there is also a check to see if the test is owned by a role the current user has

**Comment by barreiro** [comment]
I believe the problem here is that the action (and the corresponding logs) for a new test are executed with id `-1`. They should execute with the id of the newly created test instead, then a user with `tester` role for the test will be able to query `/api/log/action/{testId}`. Otherwise it will only be accessible for `admin` users.
