### ISSUE TITLE
Node vesion used by Github Action.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Horreum#1423]
**Describe the bug**

Builds are failing due to the version of Node use to run the action. Currently 16. 

```
build (ubuntu-latest)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: 
actions/upload-artifact@v3
. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

**Node**

What is the version of Node ?

```
16
```

**Comment by lampajr** [comment]
Hey @whitingjr, I double checked and it seems that just two actions (that we are using) are still running on `node16`:
* **Backporting**: I already tagged a new version, ie. `4.5.2` so we can simply update to that version (right now we are on `4.5.1`)
* **Welcome**: I opened a PR [upstream](https://github.com/wow-actions/welcome/pull/12), let's see if we can get that in otherwise we might consider switching to a different one.

**Comment by whitingjr** [comment]
@lampajr this is good to hear. do you want to create a PR for the `Backporting` action ? Then version bump `Welcome` when available from upstream.

**Comment by lampajr** [comment]
> @lampajr this is good to hear. do you want to create a PR for the `Backporting` action ? Then version bump `Welcome` when available from upstream.

Sure, here it is: https://github.com/Hyperfoil/Horreum/pull/1487

**Comment by lampajr** [comment]
> * **Welcome**: I opened a PR [upstream](https://github.com/wow-actions/welcome/pull/12), let's see if we can get that in otherwise we might consider switching to a different one.

Just a quick update, this has been finally merged! 🚀
