### ISSUE TITLE
Exhausted AMQP Connections.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Horreum#2103]
**Describe the bug**

 Horreum is exhausting AMQP connections. This prevents the processing of messages from queues.

**To Reproduce**

None.

**Version**

```
0.15.6
```

**Comment by johnaohara** [comment]
@whitingjr wdym by exhausting connections? is there an error message?

**Comment by whitingjr** [comment]
@johnaohara  There has been talk of OptimisticLockException in FingerprintDAO. @barreiro do you have more details ?

**Comment by lampajr** [comment]
To avoid any confusion, isn't this related to the the fact that Horreum is not currently properly managing AMQP connections (specifically when there are exceptions)? 

The OptimisticLockException is just an example of issue that caused the connections to be disconnected, but this is not the root cause of the problem
