### ISSUE TITLE
Add podman-compose compatability integration. 

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Horreum#221]
Add integration allowing podman-compose to be used.

 This is an alternative to docker-compose.
 Provide a system property that will enable using podman-compose files. For both infra and integration-test projects.

**Comment by rvansa** [comment]
I guess you mean to use the podman-compose scripts in testsuite, right? You will need to first build the app (quarkus) with podman instead of docker as the image needs to be in podman repository. Regrettably AFAIK this is not supported in Quarkus: https://quarkus.io/guides/container-image#docker

And then let testcontainers use that.

Please make sure that this works on machines where both docker and podman are installed, without `alias docker = podman`.

**Comment by whitingjr** [comment]
> I guess you mean to use the podman-compose scripts in testsuite, right?

That's right.

**Comment by jesperpedersen** [comment]
This has been documented
