### ISSUE TITLE
Change detection loads all labels without a filter.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Horreum#241]
While the number of labels is relatively low the page loads at a usable speed.
 As time goes by the label count will increase. Making the page slower.
 Adding a filter (drop down select box or something) for Labels filtered by schema, All schemas being the last option.

**Comment by rvansa** [comment]
I've added filtering for schemas to the footer for easier search, and customized the filter function to search for a substring (any place) rather than just for labels starting with the typed value. I don't think that fetching the data from server is the bottleneck here - could you link a page that feels slow? It's possible that something with multiple `<Labels ... />` fetches the list of labels multiple times; I am relying on browser caching to save us from this but maybe Horreum is not hinting the browser enough.

**Comment by rvansa** [comment]
There's several things that could get slow: DB lookup, JSON transfer, rendering. At this point we don't see which part could be the problem, so I won't optimize prematurely.
If you find a case I could analyze & improve, or have a general UX problem with label lookup, please reopen.
