### ISSUE TITLE
min/max based change detection algorithm

### ISSUE THREAD

**Issue by jhutar** [Hyperfoil/Horreum#312]
Hello! Would you be willing to add one more change detection algorithm? This is what we are using as of now:

Imagine test results like this (let's say it is a duration in seconds) where FAIL means that result was detected as a change and was confirmed by user - or whatever is Horreum terminology of marking a result as FAIL:

```
100 PASS
103 PASS
97 PASS
100 PASS
101 PASS
112 FAIL
103 PASS
98 PASS
99 PASS
101 PASS
```

Let's say new result is `107`.

Algorithm is configured to consider floating window of last, say, 5 passing results with same test parameters (in Horreum terminology I guess it means "with same fingerprinting labels").

So algorithm is supposed to consider numbers 101, 99, 98,103 and 101 (112 is skipped, because it was marked as FAIL), so MIN is 98 and MAX is 103.

As new result is 107, it is outside of the "human curated safe range", so result is FAIL. If the new result would be, say, 102, it would be PASS.

**Comment by johnaohara** [comment]
@jhutar how would min/max change detection work? Could you provide an example use case of how you would use this? 

It is possible at the moment to define threshold-based change detection and to define functions for manipulating data for change detection. It might be that the use case you are thinking of could be supported with existing functionality

**Comment by jhutar** [comment]
Hello @johnaohara sorry for not providing description. I was writing the ticket yesterday and submitted it by accident before finishing and before I fixed it, I was called off. Sorry for confusion!

**Comment by jesperpedersen** [comment]
Hi @jhutar - Would you be able to supply a patch for this ?

**Comment by rvansa** [comment]
@jhutar Actually you're asking for two things:

1) Test if last result is within the bounds of last 5 results: that wouldn't be too hard to do, but it means that without a failure the range will get more and more narrow. If you take a series with random error (gaussian distribution but that doesn't really matter) you will have failure every 10 runs or so. Do you really want to have a statistically-forced failures? What's the point of this test?

2) Right now Horreum would detect single outlier result as two changes - once because the outlier happened and second time because it was fixed. You'd like to ignore outliers for the purposes of getting historical data. This would require another object (or manual flag on Change) to 'restart' the series when the change in the metric is acknowledged. Alternatively we could manually flag the datapoint as outlier and ignore it completely in the future. We would also need to persist that in a different table because datapoints are recalculated (a new row with new ID) when the dataset is retransformed, when you change the variable definition etc.

**Comment by johnaohara** [comment]
> 2\. Alternatively we could manually flag the datapoint as outlier and ignore it completely in the future. 

There is another potential consideration. If we are looking to create a "human curated safe range" and conflate "no-change"/"change" detected to PASS/FAIL, we would need to be able to override the automated PASS/FAIL determination. atm, we can confirm/delete the detected change, i.e. curate the "FAILS", but we can not manually record a "no-change" datapoint as "FAILED" and therefore curate the "PASSES"

**Comment by jhutar** [comment]
Hello @jesperpedersen. I do not plan to work on it.

I assume effort for this change is above what I'm willing to invest. It might change if I'm asked to work on it, but given what I know (and more importantly what I do not know), if I would be asked to work on it, I would not consider it responsible use of my time (it is completely different stack).

**Comment by jhutar** [comment]
Hello @johnaohara . Exactly. To make this work, we might need to be able to mark "no change" as a "confirmed change". Ideally with a way to add some comment to every confirmed change to note down details about the error.

**Comment by jhutar** [comment]
During processing your comments, I realized I was probably trying to push my mindset about the workflow to your product which is not correct. It is just an other way how to do the things.

In my mind, in our workflow, I considered a "change" as a failure if not proved otherwise. In Horreum, change is simply a detected change (well, that is in the name already :)).

Please feel free to close if the request does not make sense to you.

**Comment by rvansa** [comment]
I am closing this in favor of https://github.com/Hyperfoil/Horreum/issues/335
If there are other aspect crystalizing from this discussion (thanks for it!) please open another issue.
