### ISSUE TITLE
Order of query options. 

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Horreum#573]
**Feature idea.**

Change the order of items in DDLB on the Run/Dataset page.
The least useful item in the list is `js`. This option is not the JSONpath syntax used in the database. Which means using the first activity when the page loads is to switch to `jsonb_path_query_first` or `jsonb_path_query_array`.

Secondly for new users they will be confused why the path expression (using the default) created on this page will not work in the database. It is a time sink.

http://blah.com/run/17938

**Describe the solution you'd like**

The new order of items

1. jsonb_path_query_first
2. jsonb_path_query_array
3. js

Horreum version:
0.7.9

**Comment by johnaohara** [comment]
I was discussing this with @willr3 the other day, I think we should standardize on a json path expression implementation and use that consistently throughout Horreum.

The issue we have is that postgres jsonb_path syntax is not as complete as the js syntax, but we use jsonb syntax because we can run it in the database and not pass json objects as strings between the app and the database
