### ISSUE TITLE
Refactor out the ui services out of -api

### ISSUE THREAD

**Issue by stalep** [Hyperfoil/Horreum#664]
To make a clear distinction of what is included in the "client" and "ui" api we can split the ui specific services out to a -ui module that depends on -api.
This enables us to easily separate the generation of the openapi files.

**Comment by johnaohara** [comment]
As mentioned on chat,

everything with JsonNode. ArrayNode, ObjectNode types are problematic, and we should make sure we try to split them out into a UI-api in the first instance where we can

we should also look at where we return `jakarta.ws.rs.core.Response` and probably change to `org.jboss.resteasy.reactive.RestResponse`, because we can have a typed response.
`jakarta.ws.rs.core.Response` is not generic

**Comment by johnaohara** [comment]
And also we should validate the non-ui api openapi schema,  set this to `false`: 
https://github.com/Hyperfoil/Horreum/blob/master/horreum-api/pom.xml#L98

**Comment by jesperpedersen** [comment]
Ideally we should only use "core" data types to Java or the platform.

It could be good to spend a bit of time to look at other platforms way of doing it such that we make sure that we can make clients work across programming languages

**Comment by jesperpedersen** [comment]
I have looked at how we integrate with other programming languages and frameworks.

For all the JSON data I think we have to rely on `java.lang.String`, and then we need to validate in each of the API endpoints.

I would prefer the Jakarta classes, but the RestEasy one is ok as well
