### ISSUE TITLE
"Test label calculation" doesn't work with "All match" (array) extractors

### ISSUE THREAD

**Issue by dustinblack** [Hyperfoil/Horreum#907]
**Describe the bug**

When using a combination function with an extractor in a label that is set to use `All matches` and therefore return an array, The `Test label calculation` button will return an error on any function that attempts to treat the extractor value as an array, as though the value were instead a scalar.

I'm guessing that whether `First match` or `All matches` is set on an extractor, the test always runs with an assumption of `First match`.

The functions appear to work as expected in other views/reports, just not with the test.

![image](https://github.com/Hyperfoil/Horreum/assets/10656942/ceb1b00e-6505-4a21-b5f1-ffd9c06125bf)
![image](https://github.com/Hyperfoil/Horreum/assets/10656942/1460722e-dd7a-47d4-8bc6-54ed7b8ed5ab)

**To Reproduce**

Set any label extractor to `All matches` and write a combination function that performs an operation on the value as an array, and click the `Test label calculation` button.

**Version**

Current hosted: 0.9.6

**OS**

Fedora 39

**Browser**

Brave 1.60.114

**Comment by lampajr** [comment]
I can confirm what Dustin already said, the issue seems happening just in the `Test label calculation` action and the motivation is actually that the `array` field is ignored in the backed due to mismatch in the naming convention between the psql type `Extractor` and the `Extractor` DTO.

The type is created with field named `isarray`: https://github.com/Hyperfoil/Horreum/blob/e250947f4eff0779e2f637d61f54b794d1f5ef4c/horreum-backend/src/main/resources/db/changeLog.xml#L3551-L3553

but the `Extractor` class defines a `array` field: https://github.com/Hyperfoil/Horreum/blob/e250947f4eff0779e2f637d61f54b794d1f5ef4c/horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/Extractor.java#L23

Therefore, during the `previewLabel` action the extractor is serialized from the `Extractor` DTO: https://github.com/Hyperfoil/Horreum/blob/e250947f4eff0779e2f637d61f54b794d1f5ef4c/horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/DatasetServiceImpl.java#L351

And then injected into the `LABEL_PREVIEW` query: https://github.com/Hyperfoil/Horreum/blob/e250947f4eff0779e2f637d61f54b794d1f5ef4c/horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/DatasetServiceImpl.java#L359-L363

The issue can be easily reproduced with the actual query in the psql:
```bash
horreum=> SELECT * FROM jsonb_populate_recordset(NULL::extractor, '[{"name":"dracs","jsonpath":"$.qdup.state.servers.name","array":true}]'::jsonb);
 name  |             jsonpath              | isarray 
-------+-----------------------------------+---------
 dracs | $."qdup"."state"."servers"."name" | 
(1 row)
```
The `isarray` is empty, but if using correct dto:
```bash
horreum=> SELECT * FROM jsonb_populate_recordset(NULL::extractor, '[{"name":"dracs","jsonpath":"$.qdup.state.servers.name","isarray":true}]'::jsonb);
 name  |             jsonpath              | isarray 
-------+-----------------------------------+---------
 dracs | $."qdup"."state"."servers"."name" | t
(1 row)

```

**Conclusion**

Here I see two options:
1. Fix the DTO, change from `array` to `isarray`
   * This is the cleaner option but would need t ochange the openapi schema, not the api itself but the object
2. Temporarily add the following line to convert `array` to `isarray` before injecting the param in the query (this is actually dirty but less risky, especially if we want this in `0.12`)
```java
          extractors = Util.OBJECT_MAPPER.writeValueAsString(label.extractors);
+         extractors = extractors.replace("array", "isarray");
```

@johnaohara wdyt?

**Comment by lampajr** [comment]
Or 3rd option:
3. Alter the type into the database by renaming the field from `isarray` to `array`

**Comment by johnaohara** [comment]
@lampajr i would go with option (1).  workarounds like (2) tend to stick around and make the data model less easy to comprehend.  with option (3) i would be concerned about reserved words in the DB

semantically, the field is to determine if the result is an array or not, so isArray is the correct field name in this case.

we still have time to get this in 0.12.  The UI code will need updating to change `array` -> `isArray`

**Comment by lampajr** [comment]
> @lampajr i would go with option (1). workarounds like (2) tend to stick around and make the data model less easy to comprehend. with option (3) i would be concerned about reserved words in the DB
> 
> semantically, the field is to determine if the result is an array or not, so isArray is the correct field name in this case.
> 
> we still have time to get this in 0.12. The UI code will need updating to change `array` -> `isArray`

+1 I totally agree with you, I am already working on option 1!
